name: mywallet
description: a  wallet support ERC4337
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  web3dart: ^2.5.1
  eth_sig_util: ^0.0.9
  http: ^0.13.5
  steel_crypt: ^3.0.0+1
  pointycastle: ^3.6.2
  dio: ^4.0.6

  get: ^4.6.5

  # UI
  modal_bottom_sheet: ^3.0.0-pre
  qr_flutter: ^4.0.0
  phosphor_flutter: ^1.4.0
  bot_toast: ^4.0.2

  share_plus: ^6.2.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    -
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf
    - family: GilroyBlack
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Black.ttf
    - family: ProcrastinatingPixie
      fonts:
        - asset: assets/fonts/ProcrastinatingPixie/ProcrastinatingPixie.ttf
